spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Chatroom?allowPublicKeyRetrieval=true
    username: root
    password: tlx200057
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  security:
    login:
      page: /login
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  ##该问题是由于SpringBoot整合Swagger时，SpringBoot版本与 springfox版本不兼容导致的！

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # 排序方式为首字母
    tags-sorter: alpha
    # 使用增强order属性进行排序，或者不设置该参数( @ApiOperationSupport(order = n)直接生效)
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    #组名可以自己设置
    - group: 'default'
      paths-to-match: '/**'
      # controller所在包
      packages-to-scan: com.knifej.test.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN
